### ISSUE TITLE
Bug: Version should not be a float

### ISSUE THREAD

**Issue by ktechmidas** [dashpay/rs-tenderdash-abci#108]
### What went wrong?

When we build on Ubuntu with protobug installed from apt, we get:

` Caused by:
  process didn't exit successfully: `/home/runner/work/dash-evo-tool/dash-evo-tool/target/release/build/tenderdash-proto-060052498a8d720c/build-script-build` (exit status: 1)
  --- stderr
Error: r] => failed to parse protoc version libprotoc 3.12.4`

Digging into the code, we have defined the minimum version as a float: https://github.com/dashpay/rs-tenderdash-abci/blob/a6da8438116a30e56336afb1bb01cbb71aaffc62/proto-compiler/src/constants.rs#L4

In Ubuntu and other OS's, versions are different. Ubuntu is 3.12.4 which is _not_ a float, so when we do the comparison it fails: https://github.com/dashpay/rs-tenderdash-abci/blob/a6da8438116a30e56336afb1bb01cbb71aaffc62/proto-compiler/src/functions.rs#L364

### Steps to reproduce
`apt install protobuf-compiler libprotobuf-dev` on Ubuntu
Attempt to compile

### Definition of "done"

It will compile properly on ubuntu

**Comment by lklimek** [comment]
We only support protoc installed from https://github.com/protocolbuffers/protobuf/releases . The one shipped with Ubuntu is not supported.
